version: '3'

services:
  app:
    build: .
    expose:
      - ${PORT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    ports:
      - ${PORT}:${PORT}
    command:
      - /bin/sh
      - -c
      - |
        npm run prisma:generate
        npm run prisma:migrate
        npm run prisma:seed
        npm run build
        npm run start:prod

  database:
    image: postgres:latest
    restart: always
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
