version: '3'

services:
  app:
    image: node:16-alpine
    working_dir: /app
    expose:
      - ${PORT}
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - '3000:3000'
    command:
      - npm run prisma:migrate
      - npm run prisma:seed
      - npm start

  db:
    image: postgres:latest
    restart: always
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
